import type {
  Booking,
  Enquiry,
  Feedback,
  Product,
  SiteContent,
  GalleryItem,
  JourneyMilestone,
  Achievement,
  SustainabilityContent,
  User,
  ActivityItem,
  QrSettings,
  AgencySettings,
  LocalDiscoveryContent,
  ContactSettings,
} from './types';

export const CURRENT_USER = {
  name: 'MBGA Administrator',
  email: 'admin@mbga.in',
  role: 'Super Admin' as const,
  avatar: 'MA',
};

export const products: Product[] = [
  {
    id: 'prod-19kg',
    name: '19 kg Commercial LPG Cylinder',
    slug: '19kg-commercial-lpg',
    category: 'Commercial',
    cylinderCapacity: '19 kg',
    description: 'Reliable LPG for restaurants, hotels, caterers and commercial kitchens.',
    features: ['ISI-marked cylinder', 'Tamper-proof seal', 'Planned delivery support'],
    image: '/assets/industrial/use-restaurant.png',
    availability: 'In Stock',
    displayOrder: 1,
    archived: false,
  },
  {
    id: 'prod-35kg',
    name: '35 kg Commercial LPG Cylinder',
    slug: '35kg-commercial-lpg',
    category: 'Commercial',
    cylinderCapacity: '35 kg',
    description: 'Higher capacity solution for busy kitchens and growing businesses.',
    features: ['Higher capacity', 'Fewer refill cycles', 'Business supply support'],
    image: '/assets/industrial/use-canteen.png',
    availability: 'In Stock',
    displayOrder: 2,
    archived: false,
  },
  {
    id: 'prod-475kg',
    name: '47.5 kg Industrial LPG Cylinder',
    slug: '47-5kg-industrial-lpg',
    category: 'Industrial',
    cylinderCapacity: '47.5 kg',
    description: 'Industrial LPG support for manufacturing and process-heating requirements.',
    features: ['Industrial application', 'Requirement-led supply', 'Safety-first handling'],
    image: '/assets/industrial/use-industrial.png',
    availability: 'Limited',
    displayOrder: 3,
    archived: false,
  },
];

export const bookings: Booking[] = [
  {
    id: 'BKG-2024-1042',
    customerName: 'Amit Patel',
    businessName: 'Spice Garden Restaurant',
    email: '',
    phone: '+91 98250 11111 (demo)',
    cylinderType: '19 kg Commercial',
    quantity: 4,
    deliveryArea: 'Vesu, Surat',
    source: 'Website',
    date: '2024-08-19T10:30:00',
    status: 'New',
    notes: ['Customer requested morning delivery before 9 AM.'],
  },
  {
    id: 'BKG-2024-1041',
    customerName: 'Sneha Desai',
    businessName: 'Desai Caterers',
    email: '',
    phone: '+91 98250 22222 (demo)',
    cylinderType: '35 kg Commercial',
    quantity: 2,
    deliveryArea: 'Adajan, Surat',
    source: 'WhatsApp',
    date: '2024-08-19T09:15:00',
    status: 'Confirmed',
    notes: ['Bulk order for weekend event. Confirmed delivery slot 11 AM-12 PM.'],
  },
  {
    id: 'BKG-2024-1040',
    customerName: 'Mahesh Joshi',
    businessName: 'Joshi Fabrication Works',
    email: '',
    phone: '+91 98250 33333 (demo)',
    cylinderType: 'Bharat Metal Cutting Gas',
    quantity: 3,
    deliveryArea: 'Sachin GIDC, Surat',
    source: 'QR',
    date: '2024-08-18T16:45:00',
    status: 'Processing',
    notes: ['Industrial customer. Invoice to be sent to accounts email.'],
  },
  {
    id: 'BKG-2024-1039',
    customerName: 'Kiran Mehta',
    businessName: 'Mehta Steel Industries',
    email: '',
    phone: '+91 98250 44444 (demo)',
    cylinderType: '47.5 kg Industrial',
    quantity: 6,
    deliveryArea: 'Hazira, Surat',
    source: 'Website',
    date: '2024-08-18T14:20:00',
    status: 'Delivered',
    notes: ['Delivered on schedule. Customer signed digital receipt.'],
  },
  {
    id: 'BKG-2024-1038',
    customerName: 'Rohit Shah',
    businessName: 'Shah Hotel & Restaurant',
    email: '',
    phone: '+91 98250 55555 (demo)',
    cylinderType: '19 kg Commercial',
    quantity: 8,
    deliveryArea: 'Varachha, Surat',
    source: 'WhatsApp',
    date: '2024-08-18T11:00:00',
    status: 'Delivered',
    notes: ['Regular customer. Monthly contract refill.'],
  },
  {
    id: 'BKG-2024-1037',
    customerName: 'Priya Gandhi',
    businessName: 'Gandhi Event Planners',
    email: '',
    phone: '+91 98250 66666 (demo)',
    cylinderType: '35 kg Commercial',
    quantity: 5,
    deliveryArea: 'Pal, Surat',
    source: 'Website',
    date: '2024-08-17T15:30:00',
    status: 'Cancelled',
    notes: ['Customer cancelled â€” event postponed to next month.'],
  },
  {
    id: 'BKG-2024-1036',
    customerName: 'Vimal Thakkar',
    businessName: 'Thakkar Kitchen Equipments',
    email: '',
    phone: '+91 98250 77777 (demo)',
    cylinderType: '19 kg Commercial',
    quantity: 3,
    deliveryArea: 'Olpad, Surat',
    source: 'QR',
    date: '2024-08-17T09:00:00',
    status: 'Delivered',
    notes: [],
  },
  {
    id: 'BKG-2024-1035',
    customerName: 'Nilesh Bhatt',
    businessName: 'Bhatt Welding Services',
    email: '',
    phone: '+91 98250 88888 (demo)',
    cylinderType: 'Bharat Metal Cutting Gas',
    quantity: 2,
    deliveryArea: 'Udhna, Surat',
    source: 'Website',
    date: '2024-08-16T13:15:00',
    status: 'Processing',
    notes: ['First-time customer. KYC documents verified.'],
  },
];

export const enquiries: Enquiry[] = [
  {
    id: 'ENQ-2024-0231',
    customerName: 'Farhan Qureshi',
    email: 'farhan.qureshi.demo@email.com',
    phone: '+91 98250 99999 (demo)',
    enquiryType: 'Bulk Supply Quote',
    subject: 'Monthly bulk supply requirement for factory',
    message:
      'We run a food processing unit in Sachin GIDC and need approximately 200 kg LPG per month. Please share bulk pricing and contract terms.',
    assignedStaff: 'Rajesh Sharma',
    status: 'Open',
    priority: 'High',
    internalNotes: ['Lead qualifies for bulk contract tier. Send industrial rate card.'],
    date: '2024-08-19T11:00:00',
  },
  {
    id: 'ENQ-2024-0230',
    customerName: 'Lata Iyer',
    email: 'lata.iyer.demo@email.com',
    phone: '+91 98251 12345 (demo)',
    enquiryType: 'New Connection',
    subject: 'Commercial connection for new restaurant',
    message:
      'Opening a new restaurant in Vesu next month. Need a commercial LPG connection with 2-3 cylinders per week. What documents are required?',
    assignedStaff: 'Priya Admin',
    status: 'In Progress',
    priority: 'Medium',
    internalNotes: ['Sent document checklist. Awaiting KYC upload.'],
    date: '2024-08-18T10:20:00',
  },
  {
    id: 'ENQ-2024-0229',
    customerName: 'Sanjay Agarwal',
    email: 'sanjay.agarwal.demo@email.com',
    phone: '+91 98251 23456 (demo)',
    enquiryType: 'Pricing',
    subject: 'Current price for 47.5 kg industrial cylinder',
    message: 'Please share the latest price and delivery charges for 47.5 kg industrial cylinders to Hazira.',
    assignedStaff: 'Priya Admin',
    status: 'Resolved',
    priority: 'Low',
    internalNotes: ['Shared rate card via email. Customer acknowledged.'],
    date: '2024-08-17T14:00:00',
  },
  {
    id: 'ENQ-2024-0228',
    customerName: 'Deepak Nair',
    email: 'deepak.nair.demo@email.com',
    phone: '+91 98251 34567 (demo)',
    enquiryType: 'Safety Concern',
    subject: 'Cylinder valve seems loose',
    message:
      'The valve on the cylinder delivered yesterday feels slightly loose when turning. Is this normal or should it be replaced?',
    assignedStaff: 'Rajesh Sharma',
    status: 'Open',
    priority: 'Urgent',
    internalNotes: ['Safety priority. Dispatch technician for inspection today.'],
    date: '2024-08-19T08:30:00',
  },
  {
    id: 'ENQ-2024-0227',
    customerName: 'Anita Rao',
    email: 'anita.rao.demo@email.com',
    phone: '+91 98251 45678 (demo)',
    enquiryType: 'Delivery Schedule',
    subject: 'Change delivery day for monthly contract',
    message: 'Can we move our regular delivery from Monday to Wednesday starting next month?',
    assignedStaff: 'Support Team',
    status: 'Closed',
    priority: 'Low',
    internalNotes: ['Schedule updated in system. Confirmed with customer.'],
    date: '2024-08-15T12:00:00',
  },
];

export const feedback: Feedback[] = [
  {
    id: 'FBK-2024-0089',
    customerName: 'Amit Patel',
    email: 'amit.patel.demo@email.com',
    phone: '+91 98250 11111 (demo)',
    rating: 5,
    message:
      'Excellent service! The cylinder was delivered within 6 hours of booking. The delivery staff was professional and helpful.',
    status: 'New',
    date: '2024-08-19T12:00:00',
    type: 'Feedback',
  },
  {
    id: 'FBK-2024-0088',
    customerName: 'Kiran Mehta',
    email: 'kirn.mehta.demo@email.com',
    phone: '+91 98250 44444 (demo)',
    rating: 4,
    message:
      'Good service overall, but the online booking form could be simpler. Had to call to confirm the order. Otherwise satisfied.',
    status: 'Reviewed',
    reply: 'Thank you for the feedback. We are working on simplifying the booking form.',
    date: '2024-08-18T16:30:00',
    type: 'Feedback',
  },
  {
    id: 'FBK-2024-0087',
    customerName: 'Priya Gandhi',
    email: 'priya.gandhi.demo@email.com',
    phone: '+91 98250 66666 (demo)',
    rating: 2,
    message:
      'My booking was cancelled without clear communication. Had to follow up multiple times. Please improve the notification system.',
    status: 'Resolved',
    reply:
      'We apologize for the inconvenience. The cancellation was due to a scheduling conflict. We have updated our process to send automatic SMS notifications.',
    date: '2024-08-17T10:15:00',
    type: 'Complaint',
  },
  {
    id: 'FBK-2024-0086',
    customerName: 'Mahesh Joshi',
    email: 'mahesh.joshi.demo@email.com',
    phone: '+91 98250 33333 (demo)',
    rating: 5,
    message:
      'The metal cutting gas performs very well. Flame temperature is consistent and we have reduced our slag cleanup time significantly.',
    status: 'Resolved',
    reply: 'Glad to hear it! Thank you for choosing Bharatgas.',
    date: '2024-08-16T14:45:00',
    type: 'Feedback',
  },
  {
    id: 'FBK-2024-0085',
    customerName: 'Rohit Shah',
    email: 'rohit.shah.demo@email.com',
    phone: '+91 98250 55555 (demo)',
    rating: 3,
    message: 'Delivery was on time but the cylinder had a small dent. Functionally fine but please check before dispatch.',
    status: 'New',
    date: '2024-08-15T09:20:00',
    type: 'Complaint',
  },
];

export const siteContent: SiteContent = {
  agencyIntro:
    'Madhav Bharat Gas Agency provides dependable non-domestic LPG supply, cylinder exchange coordination and responsive support to businesses in Gurugram.',
  phonePrimary: '+91 98765 43210',
  phoneSecondary: '+91 98765 43211',
  email: 'help@bharatgasagency.in',
  officeAddress: 'Shop 12, Main Market Road, Sector 70, Gurugram, Haryana 122101',
  businessHours: 'Monday to Saturday: 9:00 AM â€“ 6:00 PM | Sunday: Closed',
  whatsappNumber: '919876543210',
  seoTitle: 'Madhav Bharat Gas Agency | Commercial & Industrial LPG',
  seoDescription:
    'Authorized Bharatgas distributor for dependable non-domestic LPG assistance in Gurugram.',
  bharatgasLogoUrl: '/assets/brands/bharatgas-logo.svg',
  bharatgasLogoAlt: 'Bharatgas logo',
  mbgaLogoUrl: '/assets/brands/mbga-logo.svg',
  mbgaLogoAlt: 'Madhav Bharat Gas Agency logo',
  heroSlides: [
    {
      id: 'hero-1',
      title: 'Dependable LPG Supply for Your Business',
      subtitle: 'Authorized Bharatgas non-domestic LPG supply with local MBGA support.',
      image: '/assets/industrial/industrial-hero.png',
      ctaText: 'Contact MBGA',
      ctaLink: '/contact',
      displayOrder: 1,
      published: true,
    },
    {
      id: 'hero-2',
      title: 'Bulk & Cylinder Supply, Planned Around Your Shifts',
      subtitle: 'Scheduled dispatch and cylinder exchange for manufacturing units, processing plants and large commercial kitchens.',
      image: '/assets/industrial/industrial-plant.png',
      ctaText: 'View LPG Products',
      ctaLink: '/products',
      displayOrder: 2,
      published: true,
    },
    {
      id: 'hero-3',
      title: 'Safety-Led Handling at Every Site',
      subtitle: 'Manifold installations, routine connection checks and clear handling guidance for your site team.',
      image: '/assets/industrial/cylinder-bank.png',
      ctaText: 'Our Safety Approach',
      ctaLink: '/sustainability',
      displayOrder: 3,
      published: true,
    },
  ],
};

export const galleryItems: GalleryItem[] = [
  {
    id: 'gal-1',
    type: 'Image',
    url: '/assets/industrial/business-support.png',
    thumbnailUrl: '',
    category: 'Agency',
    altText: 'MBGA account team coordinating commercial LPG supply',
    caption: 'Business account support',
    displayOrder: 1,
    status: 'Published',
  },
  {
    id: 'gal-2',
    type: 'Image',
    url: '/assets/industrial/bulk-delivery.png',
    thumbnailUrl: '',
    category: 'Delivery',
    altText: 'Bulk LPG tanker and cylinder dispatch truck leaving the yard',
    caption: 'Bulk and cylinder dispatch',
    displayOrder: 2,
    status: 'Published',
  },
  {
    id: 'gal-3',
    type: 'Image',
    url: '/assets/industrial/industrial-safety.png',
    thumbnailUrl: '',
    category: 'Safety',
    altText: 'Technician checking a commercial LPG manifold with a gas detector',
    caption: 'Site safety inspection',
    displayOrder: 3,
    status: 'Published',
  },
  {
    id: 'gal-4',
    type: 'Image',
    url: '/assets/industrial/cylinder-bank.png',
    thumbnailUrl: '',
    category: 'LPG Service',
    altText: 'Twin-bank industrial LPG cylinder manifold with changeover regulator',
    caption: 'Industrial manifold installation',
    displayOrder: 4,
    status: 'Published',
  },
  {
    id: 'gal-5',
    type: 'Image',
    url: '/assets/industrial/commercial-kitchen.png',
    thumbnailUrl: '',
    category: 'Commercial',
    altText: 'Commercial hotel kitchen line running on 19 kg LPG cylinders',
    caption: 'Commercial kitchen supply',
    displayOrder: 5,
    status: 'Published',
  },
  {
    id: 'gal-6',
    type: 'Image',
    url: '/assets/industrial/industrial-plant.png',
    thumbnailUrl: '',
    category: 'Industrial',
    altText: 'Bulk LPG installation and cylinder bank at an industrial site',
    caption: 'Industrial site installation',
    displayOrder: 6,
    status: 'Published',
  },
  {
    id: 'gal-7',
    type: 'Image',
    url: '/assets/industrial/use-small-shop.png',
    thumbnailUrl: '',
    category: 'Commercial',
    altText: 'Tea and snacks stall running a burner from a 5 kg commercial LPG cylinder',
    caption: 'Small shop and stall supply',
    displayOrder: 7,
    status: 'Published',
  },
];

export const journeyMilestones: JourneyMilestone[] = [
  {
    id: 'jrn-1',
    year: 'Foundation',
    category: 'Agency Service',
    title: 'Madhav Bharat Gas Agency',
    description: 'MBGA began serving local non-domestic LPG customers as an authorized Bharatgas distributor.',
    brand: 'MBGA',
    icon: 'Building2',
    imageUrl: '',
    imageAlt: '',
    displayOrder: 1,
    published: true,
    featured: true,
  },
  {
    id: 'jrn-2',
    year: 'Growth',
    category: 'Customer Success',
    title: 'Business Supply Support',
    description: 'Commercial assistance expanded across restaurants, caterers and industrial customers.',
    brand: 'MBGA',
    icon: 'TrendingUp',
    imageUrl: '',
    imageAlt: '',
    displayOrder: 2,
    published: true,
    featured: false,
  },
  {
    id: 'jrn-3',
    year: 'Today',
    category: 'Brand Network',
    title: 'MBGA Ã— Bharatgas',
    description: 'Local coordination backed by the established Bharatgas product ecosystem.',
    brand: 'Bharatgas',
    icon: 'Flame',
    imageUrl: '',
    imageAlt: '',
    displayOrder: 3,
    published: true,
    featured: true,
  },
];

export const achievements: Achievement[] = [
  {
    id: 'ach-1',
    type: 'Recognition',
    title: 'Authorized Bharatgas Distributor',
    description: 'Local non-domestic LPG support connected to the Bharatgas network.',
    year: 'MBGA',
    brand: 'Bharatgas',
    imageUrl: '/assets/certificates/certificate.svg',
    published: true,
  },
  {
    id: 'ach-2',
    type: 'Milestone',
    title: 'Single-Window Business Support',
    description: 'Enquiry, requirement review and service assistance through one local team.',
    year: 'MBGA',
    brand: 'MBGA',
    imageUrl: '',
    published: true,
  },
];

export const sustainabilityContent: SustainabilityContent = {
  heroTitle: 'Responsible Operations. Safer Communities.',
  heroDescription:
    'Practical LPG handling, planned service routines and clear customer guidance support responsible day-to-day operations.',
  heroImage: '/assets/industrial/bulk-delivery.png',
  heroImageAlt: 'Bulk LPG road tanker and commercial cylinder dispatch truck',
  storyTitle: 'Responsible service in every cylinder cycle',
  storyDescription:
    'MBGA focuses on the operational practices it can directly support: planned dispatch, safe handling guidance, organized cylinder exchange and responsive local assistance.',
  storyImage: '/assets/industrial/industrial-safety.png',
  storyImageAlt: 'Technician inspecting a commercial LPG cylinder manifold',
  storyPoints: [
    'Coordinate filled-cylinder delivery and empty-cylinder return.',
    'Share practical LPG handling and safety guidance.',
    'Plan service requirements to reduce avoidable emergency trips.',
  ],
  cards: [
    {
      id: 'sus-1',
      title: 'Route-Optimized Delivery',
      description:
        'Planned delivery routes reduce travel and support dependable service.',
      icon: 'Route',
      imageUrl: '',
      imageAlt: '',
      displayOrder: 1,
      published: true,
    },
    {
      id: 'sus-2',
      title: 'Reusable Cylinder Cycle',
      description:
        'Every Bharatgas cylinder is refilled, inspected, and reused multiple times, reducing single-use packaging waste.',
      icon: 'Recycle',
      imageUrl: '',
      imageAlt: '',
      displayOrder: 2,
      published: true,
    },
    {
      id: 'sus-3',
      title: 'Digital Assistance',
      description:
        'QR and WhatsApp assistance reduce paperwork and simplify customer support.',
      icon: 'MonitorSmartphone',
      imageUrl: '',
      imageAlt: '',
      displayOrder: 3,
      published: true,
    },
    {
      id: 'sus-4',
      title: 'Safety Awareness',
      description:
        'Clear customer guidance supports disciplined cylinder placement, connection checks and everyday LPG handling.',
      icon: 'ShieldCheck',
      imageUrl: '',
      imageAlt: '',
      displayOrder: 4,
      published: true,
    },
  ],
  routePlanning:
    'Delivery routes are planned around customer zones and required capacity.',
  reusableCycle:
    'Cylinder exchange and empty returns are coordinated as part of each supply cycle.',
  digitalAssistance:
    'Customers can start a pre-filled WhatsApp enquiry by scanning the MBGA booking QR.',
  supplyChainSteps: [
    { id: 'sc-1', step: 1, title: 'Enquiry', description: 'Share the business requirement.' },
    { id: 'sc-2', step: 2, title: 'Confirmation', description: 'The MBGA team confirms availability and schedule.' },
    { id: 'sc-3', step: 3, title: 'Dispatch', description: 'Inspected cylinders are prepared for delivery.' },
    { id: 'sc-4', step: 4, title: 'Exchange', description: 'Delivery and empty-cylinder return are coordinated.' },
  ],
};

export const localDiscoveryContent: LocalDiscoveryContent = {
  heading: 'Local LPG Information',
  description: 'Useful service references based on the agency location and the LPG assistance currently offered by MBGA.',
  localities: [
    { id: 'loc-sector-70', label: 'Sector 70', href: '/contact', displayOrder: 1, active: true },
    { id: 'loc-gurugram', label: 'Gurugram', href: '/contact', displayOrder: 2, active: true },
  ],
  categories: [
    { id: 'cat-commercial', label: 'Commercial LPG', href: '/products', displayOrder: 1, active: true },
    { id: 'cat-industrial', label: 'Industrial LPG', href: '/products', displayOrder: 2, active: true },
    { id: 'cat-cylinder', label: 'Cylinder Supply', href: '/products', displayOrder: 3, active: true },
  ],
  topics: [
    { id: 'topic-safety', label: 'LPG Safety', href: '/sustainability', displayOrder: 1, active: true },
    { id: 'topic-booking', label: 'Booking Assistance', href: '/contact', displayOrder: 2, active: true },
    { id: 'topic-support', label: 'Customer Assistance', href: '/contact', displayOrder: 3, active: true },
  ],
};

export const users: User[] = [
  {
    id: 'usr-1',
    name: 'Rajesh Sharma',
    email: 'admin@mbga.in',
    role: 'Super Admin',
    active: true,
    lastActive: '2024-08-19 10:45',
  },
  {
    id: 'usr-2',
    name: 'Priya Admin',
    email: 'priya@mbga.in',
    role: 'Editor',
    active: true,
    lastActive: '2024-08-19 09:20',
  },
  {
    id: 'usr-3',
    name: 'Vimal Support',
    email: 'vimal@mbga.in',
    role: 'Support Staff',
    active: true,
    lastActive: '2024-08-18 17:10',
  },
  {
    id: 'usr-4',
    name: 'Anita Viewer',
    email: 'anita@mbga.in',
    role: 'Viewer',
    active: false,
    lastActive: '2024-08-10 14:00',
  },
  {
    id: 'usr-5',
    name: 'Kiran Manager',
    email: 'kiran@mbga.in',
    role: 'Support Staff',
    active: true,
    lastActive: '2024-08-19 08:30',
  },
];

export const activityFeed: ActivityItem[] = [
  {
    id: 'act-1',
    user: 'Rajesh Sharma',
    action: 'updated booking status to',
    target: 'BKG-2024-1040 â†’ Processing',
    time: '10 min ago',
    type: 'booking',
  },
  {
    id: 'act-2',
    user: 'Priya Admin',
    action: 'replied to feedback from',
    target: 'Kiran Mehta',
    time: '32 min ago',
    type: 'feedback',
  },
  {
    id: 'act-3',
    user: 'Vimal Support',
    action: 'assigned enquiry to',
    target: 'Rajesh Sharma (ENQ-2024-0228)',
    time: '1 hour ago',
    type: 'enquiry',
  },
  {
    id: 'act-4',
    user: 'System',
    action: 'received new booking from',
    target: 'Amit Patel â€” Spice Garden Restaurant',
    time: '2 hours ago',
    type: 'booking',
  },
  {
    id: 'act-5',
    user: 'Priya Admin',
    action: 'archived product',
    target: '19 kg Cylinder (Legacy)',
    time: '3 hours ago',
    type: 'product',
  },
  {
    id: 'act-6',
    user: 'Rajesh Sharma',
    action: 'updated hero slide',
    target: 'Bulk Supply for Industrial Units',
    time: '5 hours ago',
    type: 'content',
  },
];

export const qrSettings: QrSettings = {
  whatsappNumber: '919876543210',
  defaultMessage:
    'Hello MBGA, I want to book non-domestic LPG.\nBusiness name: ____\nCylinder size: ____\nQuantity: ____\nArea: ____',
  bookingUrl: '',
};

export const agencySettings: AgencySettings = {
  agencyName: 'Madhav Bharat Gas Agency',
  tagline: 'Authorized Bharatgas Distributor â€” Commercial & Industrial LPG',
  phonePrimary: '+91 98765 43210',
  phoneSecondary: '+91 98765 43211',
  email: 'help@bharatgasagency.in',
  officeAddress: 'Shop 12, Main Market Road, Sector 70, Gurugram, Haryana 122101',
  businessHours: 'Monday to Saturday: 9:00 AM â€“ 6:00 PM | Sunday: Closed',
  whatsappNumber: '919876543210',
  facebook: '',
  instagram: '',
  linkedin: '',
  twitter: '',
  notifyNewBookings: true,
  notifyNewEnquiries: true,
  notifyNewFeedback: true,
  notifyLowStock: false,
  emailTemplateBooking:
    'Dear {{customer_name}},\n\nYour booking {{booking_id}} has been confirmed. We will deliver {{quantity}} x {{cylinder_type}} to {{delivery_area}} on {{delivery_date}}.\n\nThank you for choosing Madhav Bharat Gas Agency.',
  emailTemplateEnquiry:
    'Dear {{customer_name}},\n\nWe have received your enquiry regarding {{enquiry_type}}. Our team will respond within 24 hours.\n\nReference: {{enquiry_id}}',
  emailTemplateFeedback:
    'Dear {{customer_name}},\n\nThank you for your feedback. We value your input and will address your concern promptly.\n\nMadhav Bharat Gas Agency',
};

export const permissionsMatrix: Record<
  string,
  { view: boolean; create: boolean; edit: boolean; delete: boolean }
> = {
  'Super Admin': { view: true, create: true, edit: true, delete: true },
  Editor: { view: true, create: true, edit: true, delete: false },
  'Support Staff': { view: true, create: true, edit: true, delete: false },
  Viewer: { view: true, create: false, edit: false, delete: false },
};

export const enquiryStatusData = [
  { name: 'New', value: 18, fill: 'hsl(var(--chart-1))' },
  { name: 'In Progress', value: 12, fill: 'hsl(var(--chart-4))' },
  { name: 'Resolved', value: 24, fill: 'hsl(var(--chart-3))' },
  { name: 'Closed', value: 8, fill: 'hsl(var(--muted-foreground))' },
];

export const bookingsTrendData = [
  { day: 'Mon', bookings: 14, enquiries: 8 },
  { day: 'Tue', bookings: 18, enquiries: 11 },
  { day: 'Wed', bookings: 12, enquiries: 7 },
  { day: 'Thu', bookings: 22, enquiries: 14 },
  { day: 'Fri', bookings: 26, enquiries: 16 },
  { day: 'Sat', bookings: 31, enquiries: 19 },
  { day: 'Sun', bookings: 6, enquiries: 3 },
];

export const fallbackContactSettings: ContactSettings = {
  eyebrow: 'Contact, Booking & Feedback',
  title: 'Send Your Request Securely',
  description: 'Choose the request type. The form is validated and saved to the MBGA admin panel before any email notification is attempted.',
  callButtonText: 'Call Agency',
  emailButtonText: 'Send Email',
  submitButtonText: 'Submit to MBGA',
  statusText: 'Your request will be securely saved and shared with the MBGA support team.',
  unavailableText: 'Form currently unavailable',
  formTypes: [
    { id: 'enquiry', label: 'LPG Enquiry', enabled: true, displayOrder: 1 },
    { id: 'booking', label: 'Commercial Cylinder Booking', enabled: true, displayOrder: 2 },
    { id: 'feedback', label: 'Feedback or Complaint', enabled: true, displayOrder: 3 },
  ],
};
